name: mood_notes_app
description: A Flutter app for tracking mood entries with notes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^19.3.0
  path_provider: ^2.1.4
  csv: ^6.0.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
